default_stages: [pre-commit]
repos:
  # standard built in pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # Removes trailing whitespaces
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline
      - id: check-yaml # Loads all yaml files to verify syntax
      - id: check-added-large-files # Prevents giant files from being committed (default=500kB)
      - id: debug-statements # Removes debug statements which should never be in production
      - id: requirements-txt-fixer # Sorts entries in requirements.txt and constraints.txt and removes incorrect entry for pkg-resources==0.0.0

  # Python code formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.3
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # # Run the formatter.
      # - id: ruff-format
      #   types_or: [ python, pyi, jupyter ]

  # autoflake removes unused import statements, config in args below
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']

  # Toolkit for checking your code base against coding style (PEP8), programming errors and check cyclomatic complexity
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8

  # To enforce type hinting
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports  # Ignore missing imports: useful for third-party libraries and inter-module imports
          - --disable-error-code  # Disable the error code, which is useful for ignoring specific errors
          - no-any-unimported  # Disables the error code no-any-unimported
          - --explicit-package-bases  # Explicit package bases: useful for avoiding ambiguous type errors
        exclude: ^(tests|tooling|docs|notebooks|.*notebook.py)$
        additional_dependencies:
          - "types-PyYAML"

  # Notebook remove results
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  # Sort your imports automatically
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120", "--filter-files"]

  # Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black-jupyter
        args: ["-l", "120"]
        additional_dependencies:
          - "click==8.1.3" # Required in order for black to run

  # Run black on python code blocks in documentation files
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies:
          - "black==24.4.2"

  # SQL linter that supports many dialects
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
  # validate Markdown / RST files
  - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
      - id: rst-linter

  # Syntax update for newer Python versions
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
