trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  - script: |
      curl -LsSf https://astral.sh/uv/install.sh | sh
    displayName: 'Install uv'

  - script: |
      uv python install 3.10
    displayName: 'Set Python to 3.10 using uv'

  - script: |
      uv sync
    displayName: 'Install dependencies using uv'

  - script: |
      uv run pre-commit run --all-files
    displayName: 'Run pre-commit hooks'

  - script: |
      uv run pytest
    displayName: 'Run tests'
