name: CI/CD

on:
  pull_request:
    branches:
      - dev
      - main
  push:
    branches:
      - main

env:
  MY_SECRET: ${{ secrets.MY_SECRET }}

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync

      - name: Run pre-commit hooks
        run: uv run pre-commit run --all-files

      - name: Run tests
        run: uv run pytest

  continuous-deployment:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Demo secret usage
        run: echo "Secret value is $MY_SECRET"

      - name: Pretend to deploy
        run: echo "I'm pretending to deploy to production..."
